repositories {
    mavenLocal()
    mavenCentral()
    google() // Needed for androidx
    maven { url = "https://mymaven.bylazar.com/releases" }
    gradlePluginPortal()
    maven { url = "https://repo.dairy.foundation/releases" }
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:11.1.0'
    implementation 'org.firstinspires.ftc:Blocks:11.1.0'
    //noinspection Aligned16KB
    implementation 'org.firstinspires.ftc:RobotCore:11.1.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.1.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.1.0'
    implementation 'org.firstinspires.ftc:Hardware:11.1.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.1.0'
    implementation 'org.firstinspires.ftc:Vision:11.1.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'

    implementation "com.bylazar:fullpanels:1.0.12"
    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'

//    testImplementation 'junit:junit:6.1.0'
    testImplementation(platform("org.junit:junit-bom:6.1.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    testImplementation 'io.mockk:mockk:1.14.9'
    testImplementation 'io.mockk:mockk-android:1.14.9'
    testImplementation 'io.mockk:mockk-agent:1.14.9'
    implementation("dev.anygeneric:blazeftc:0.1.36")
    implementation("dev.frozenmilk.dairy:Mercurial:2.0.0-beta8")
}