package org.hexnibble.hexlib

import android.util.Log

/**
 * Logging object that wraps android.util.Log in order to easily sort by logs generated by TeamCode
 * and where each log was run.
 */
object L {
    @JvmStatic
    fun v(logTag: String, logString: String) {
        Log.v("HexNibble", "($logTag) $logString")
    }
    @JvmStatic
    fun d(logTag: String, logString: String) {
        Log.d("HexNibble", "($logTag) $logString")
    }
    @JvmStatic
    fun i(logTag: String, logString: String) {
        Log.i("HexNibble", "($logTag) $logString")
    }
    @JvmStatic
    fun w(logTag: String, logString: String) {
        Log.w("HexNibble", "($logTag) $logString")
    }
    @JvmStatic
    fun e(logTag: String, logString: String) {
      Log.e("HexNibble", "($logTag) $logString")
    }
}